# Generated by Django 4.0.3 on 2022-04-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='detail',
            new_name='content',
        ),
    ]
