# Generated by Django 4.0.3 on 2022-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_detail_news_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='News_Category',
        ),
        migrations.AlterModelOptions(
            name='news_category',
            options={'verbose_name': 'News Category', 'verbose_name_plural': 'News Categories'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='category',
            new_name='news_category',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_status',
            field=models.BooleanField(default=True, verbose_name='Publishing Status'),
        ),
    ]
