# Generated by Django 4.0.3 on 2022-04-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_info_tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.SlugField(max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=300)),
                ('query_resolve_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_marked_resolve', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'query',
                'verbose_name_plural': 'queries',
            },
        ),
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('is_verified', models.BooleanField(default=False)),
                ('sub_status', models.BooleanField(default=False)),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('sub_change_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
            },
        ),
        migrations.CreateModel(
            name='office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.SlugField(max_length=30, unique=True, verbose_name='Office Type')),
                ('post_code', models.IntegerField(unique=True, verbose_name='Postal Code')),
                ('address', models.CharField(max_length=100, verbose_name='Complex Address')),
                ('phone_num', models.CharField(max_length=8, verbose_name='Landline')),
                ('opening_time', models.TimeField(blank=True, default='', null=True, verbose_name='Opening Time')),
                ('closing_time', models.TimeField(blank=True, default='', null=True, verbose_name='Closing Time')),
                ('week_start_day', models.CharField(default='Monday', max_length=50, verbose_name='Week Start Day')),
                ('week_end_day', models.CharField(default='Saturday', max_length=50, verbose_name='Week End Day')),
                ('break_day', models.CharField(default='Friday', max_length=50, verbose_name='Break Day')),
                ('friday_break_start', models.TimeField(null=True, verbose_name='Break Start')),
                ('friday_break_end', models.TimeField(null=True, verbose_name='Break End')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('office_status', models.BooleanField(default=True, verbose_name='Status')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country_info_tree.district', verbose_name='District')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country_info_tree.division', verbose_name='Division')),
                ('phone_area_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country_info_tree.phn_code', verbose_name='Dialing Code')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country_info_tree.province', verbose_name='Province')),
                ('tehsil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country_info_tree.tehsil', verbose_name='City')),
            ],
            options={
                'verbose_name': 'office',
                'verbose_name_plural': 'offices',
            },
        ),
    ]
